### ISSUE TITLE
Yaml support?

### ISSUE THREAD

**Issue by janzheng** [feathersjs/schema#8]
Hi there! I was wondering if Yaml could be added as a supported schema?

**Comment by marshallswain** [comment]
Could you provide more details about how this would work? How would you define a property as an es5 getter, for example? Not sure if that’s even possible with yaml.

**Comment by daffl** [comment]
To clarify, the purpose of this project at the moment is to have a single schema definition format in native JavaScript or TypeScript. There may be conversion _from_ other formats in the future but that is not the intention right now. The idea is to reduce the number of different formats you have to manage to one, specifically the programming language we are already using.

If there is a standard YAML schema format (like JSON schema) as a target and that is what you mean, then the answer is yes, we could totally do that.
